name: Retrain Model
on:
  push:
    branches: [main]
    paths: ['data/**', 'labels/**']

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install tensorflow opencv-python
      - run: python retrain.py
      - name: Commit new model
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/
          git commit -m "Update model"
          git push
